### ISSUE TITLE
Use internal gain node in envelope

### ISSUE THREAD

**Issue by zakangelle** [zakangelle/wavedef#63]
Use an internal gain node for enveloping stuff vs. connecting directly to parameter nodes.

**Comment by trivorak** [comment]
having issues to connect the gain node to the envelope module. Set it aside to work on a different task.

**Comment by trivorak** [comment]
seems like audio has to be run thru the gain node for modulation purposes. 
gain = Headroom 
audiothru = actual modulation performed.

Lfo used to prove this method. but still working on a final design/concept
